### ISSUE TITLE
String Externalization

### ISSUE THREAD

**Issue by jayneeel** [jayneeel/Hacktober-TicTacToe#7]
Replace hardcoded string values with a more maintainable approach by storing them in the strings.xml resource file.

**Comment by MansiBhayade** [comment]
@jayneeel Could you please assign this issue to me, I want to contribute for hacktoberfest

**Comment by jayneeel** [comment]
> @jayneeel Could you please assign this issue to me, I want to contribute for hacktoberfest

It's Done
